### ISSUE TITLE
Add capability to play audio at 1.5x, 2x speed

### ISSUE THREAD

**Issue by kanwal-jaffa** [anant-jaffa/office#4]
Need capability to play audio at faster speeds

**Comment by anant-jaffa** [comment]
already has this feature

**Comment by anant-jaffa** [comment]
already have this feature

**Comment by kanwal-jaffa** [comment]
demo it to me and close the issue

**Comment by anant-jaffa** [comment]
![image](https://github.com/user-attachments/assets/6265236d-be39-4649-b2e3-c6b0596152e7)
