### ISSUE TITLE
Can text be highlighted when the audio is playing?

### ISSUE THREAD

**Issue by kanwal-jaffa** [anant-jaffa/office#5]
Would be good if the text is highlighted when the audio is playing as a way to know where the audio is at any point of time.

**Comment by anant-jaffa** [comment]
![Screenshot 2024-10-12 161331](https://github.com/user-attachments/assets/a78cab63-dd87-4963-85bf-a91225336db7)
The text is dynamically highlighted in sync with the audio.
This allows users to know the exact point in the text corresponding to the audio at any given time.
