### ISSUE TITLE
Selecting outputs in qa_summarizer 

### ISSUE THREAD

**Issue by kanwal-jaffa** [anant-jaffa/office#7]
Need to be able to select/deselect all outputs, same at the cateogry level also

**Comment by anant-jaffa** [comment]
![Screenshot 2024-10-12 161344](https://github.com/user-attachments/assets/60594f51-fda2-4dfd-aa54-93c98d55a86e)
Select a particular category, and all one-liner summaries corresponding to that category will be selected or deselected accordingly.
