### ISSUE TITLE
Dropdown menu in the landing page needs to be synced to the blob

### ISSUE THREAD

**Issue by kanwal-jaffa** [anant-jaffa/office#8]
Options that show in the landing page in dropdown should match the folder structure of blob - first with the company_name and then with quarter

**Comment by anant-jaffa** [comment]
// Issue resolved by adding a backend route that fetches available company names and quarters from the blob folder structure. The initializePage function was updated to call fetchAvailableOptions, which populates the dropdowns dynamically with the fetched data
